name: 🚀 Deploy on push (akmemis)

on:
  push:
    branches:
      - akmemis

jobs:
  deploy-akmemis:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - emis_bhadrakali
          - emis_kshitiz
          - emis_gsc
          - emis_kapan
          - emis_pinnacle
          - emis_acem
          - emis_gmc
          - emis_kalikahimalaya
          - emis_palhi
          - emis_pmcpokhara
          - emis_xavier
          - emis_gobardhan
          - emis_kalikapublic
          - emis_lawrence
          - emis_panchadewal
          - emis_spc
          - emis_lec
          - emis_triton
          - emis_gurbhakot
          - emis_radijyula
          - emis_shreekot
          - emis_myanglung
          - emis_nirmal
          - emis_nistbanepa
          - emis_vinayak
          - emis_koshi
          - emis_rabicampus
          - emis_united
          # Add more folders as needed

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Deploy to server via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 194.233.72.227
          username: akmemis
          password: ${{ secrets.AKMEMIS_PASSWORD }}
          port: 22
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/emis_rsa

            cd ~/public_html/${{ matrix.folder }}
            sh ./.scripts/deploy.sh

            ssh-agent -k
